services:
  kv:
    container_name: denorite-kv
    image: ghcr.io/denoland/denokv:latest
    command: --sqlite-path /data/denokv.sqlite serve --access-token ${DENO_KV_ACCESS_TOKEN}
    volumes:
      - kv-data:/data
    expose:
      - 4512
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  server:
    container_name: denorite-srv
    build: .
    expose:
      - 8082
      - 8081
    labels:
      - traefik.enable=true
      # Main API endpoint
      - traefik.http.routers.denorite-api.rule=Host(`${DENORITE_API_DOMAIN}`)
      - traefik.http.routers.denorite-api.entryPoints=https
      - traefik.http.services.denorite-api.loadbalancer.server.port=8082
      # Secondary endpoint
      - traefik.http.routers.denorite-secondary.rule=Host(`${DENORITE_SECONDARY_DOMAIN}`)
      - traefik.http.routers.denorite-secondary.entryPoints=https
      - traefik.http.services.denorite-secondary.loadbalancer.server.port=8081
    environment:
      - DENO_KV_URL=${DENO_KV_URL}
      - DENO_KV_ACCESS_TOKEN=${DENO_KV_ACCESS_TOKEN}
      - DENORITE_ALLOWED_ORIGIN=${DENORITE_ALLOWED_ORIGIN}
      - DENORITE_SERVER_SECRET=${DENORITE_SERVER_SECRET}
      - DENORITE_JWT_SECRET=${DENORITE_JWT_SECRET}
    volumes:
      - modules-data:/app/modules
    depends_on:
      - kv
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  kv-data:
    driver: local
    driver_opts:
      o: size=500m
      type: ext4
  modules-data:
    driver: local
    driver_opts:
      o: size=500m
      type: ext4
