services:
  app:
    container_name: denorite
    build: .
    ports:
      - "8082:8082"
      - "8081:8081"
    volumes:
      - .:/app
      - kv-data:/app/kv
      - enchantments:/app/enchantments

volumes:
  kv-data:
  enchantments:
