services:
  kv:
    container_name: denorite-kv-${CUSTOMER_ID}
    image: ghcr.io/denoland/denokv:latest
    command: --sqlite-path /data/denokv.sqlite serve --access-token ${DENO_KV_ACCESS_TOKEN}
    volumes:
      - kv_data:/data
    expose:
      - 4512
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  server:
    container_name: denorite-srv-${CUSTOMER_ID}
    build: .
    expose:
      - 8082
      - 8081
    environment:
      - DENO_KV_URL=http://denorite-kv-${CUSTOMER_ID}:4512
      - DENO_KV_ACCESS_TOKEN=${DENO_KV_ACCESS_TOKEN}
      - DENORITE_ALLOWED_ORIGIN=https://app-${CUSTOMER_ID}.cou.ai
      - DENORITE_SERVER_SECRET=${DENORITE_SERVER_SECRET}
      - DENORITE_JWT_SECRET=${DENORITE_JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-${CUSTOMER_ID}.rule=Host(`api-${CUSTOMER_ID}.cou.ai`)"
      - "traefik.http.routers.api-${CUSTOMER_ID}.service=api-${CUSTOMER_ID}"
      - "traefik.http.services.api-${CUSTOMER_ID}.loadbalancer.server.port=8081"
      - "traefik.http.routers.app-${CUSTOMER_ID}.rule=Host(`app-${CUSTOMER_ID}.cou.ai`)"
      - "traefik.http.routers.app-${CUSTOMER_ID}.service=app-${CUSTOMER_ID}"
      - "traefik.http.services.app-${CUSTOMER_ID}.loadbalancer.server.port=8082"
    volumes:
      - modules_data:/app/modules
    depends_on:
      - kv
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  kv_data:
    driver: local
    driver_opts:
      o: size=500m
      type: ext4
  modules_data:
    driver: local
    driver_opts:
      o: size=500m
      type: ext4
